max_width = 80
newline_style = "Unix"

reorder_imports = true
imports_granularity = "Item"
group_imports = "StdExternalCrate"

comment_width = 100
wrap_comments = true
merge_derives = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
