name: release

on:
  pull_request:
    branches: ["master"]

concurrency:
  group: publish-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dry-run:
    if: startsWith(github.head_ref, 'release/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
      - run: cargo check -p c32 --verbose
      - run: cargo package -p c32 --verbose
      - run: cargo publish -p c32 --dry-run --verbose
