name: version

on:
  workflow_call:
    inputs:
      base:
        description: "Name of the branch to open PR against"
        type: "string"
        default: "master"
      version:
        description: "Version to bump to (e.g. 0.3.6)"
        type: "string"
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-edit
      - id: set-version
        continue-on-error: true
        run: |
          cargo set-version ${{ input.version }}

      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          sign-commits: true
          branch: release/v${{ inputs.version }}
          commit-message: "chore(release): v${{ inputs.version }}"
          title: "chore(release): v${{ inputs.version }}"
          body: |
            # Release v${{ inputs.version }}

            ## Changes
            - Bump version to ${{ inputs.version }}

            This PR was automatically generated by the release workflow.
